namespace BideryaMvcProject.Helper.IlanHelpers
{
    public class AltKategoriEnum
    {
        public enum IlanKategori
        {
            Temizlik = 1,
            TadilatVeDekorasyon = 2,
            Nakliyat = 3,
            MontajVeTamir = 4,
            Organizasyon = 5,

        }
        public enum TemizlikAltKategori
        {
            ApartmanTemizligi = 101,
            BosEvTemizligi = 102,
            CamTemizligi = 103,
            EvTemizlik = 104,
            EvdeHaliYikama = 105,
            EvdeUtuHizmeti = 106,
            HaliYikama = 107,
            Ilaclama = 108,
            InsaatSonrasiTemizlik = 109,
            IsyeriTemizligi = 110,
            KoltukYikama = 111,
            KuruTemizleme = 112,
            MermerCilalama = 113,
            StorPerdeYikama = 114,
            YatakYikama = 115,
            YorganYikama = 116,

        }

        public enum TadilatVeDekorasyonHizmetleri
        {
            AhsapMerdiven = 201,
            AlciIsleri = 202,
            AlcipanIsleri = 203,
            AnahtarTeslimInsaaat = 204,
            AnahtarTeslimTadilat = 205,
            BahceBakimi = 206,
            BalkonFilesi = 207,
            BanyoTadilat = 208,
            BinaGuclendirme = 209,
            BoyaBadana = 210,
            CamBalkon = 211,
            CatiTadilati = 212,
            CelikEvYapimi = 213,
            CelikKapi = 214,
            CimstoneTezgah = 215,
            DogalgazTesisatiVeProjesi = 216,
            DemirKaynak = 217,
            DepremTesti = 218,
            DolapYapimi = 219,
            Dusakabin = 220,
            DuvarKagidiDoseme = 221,
            EpoksiZeminKaplama = 222,
            EvDekorasyon = 223,
            EvTadilat = 224,
            FayansDoseme = 225,
            GunesEnerjisi = 226,
            HavuzYapimi = 227,
            HazirRuloCim = 228,
            KabaInsaat = 229,
            KapiSinekligi = 230,
            KoltukDoseme = 231,
            LaminatParkeDoseme = 232,
            Mantolama = 233,
            MezarYapimi = 234,
            MimariProjeCizimi = 235,
            MobilyaBoyama = 236,
            MutfakDolabiYapimi = 237,
            MutfakTadilat = 238,
            OtomatikKepenk = 239,
            OzelMobilyaYapimi = 240,
            Panjur = 241,
            ParkeSistreCila = 242,
            ParkeTasiDoseme = 243,
            PrefabrikEvYapimi = 244,
            PVCKapiPencereBalkon = 245,
            SeramikDoseme = 246,
            SesYalitimi = 247,
            Sineklik = 248,
            StorPerde = 249,
            SuYalitimi = 250,
            SupurgelikMontaji = 251,
            SurguluKapi = 252,
            TelOrguCiti = 253,
            TenteBrandaTadilatVeDekorasyon = 254
        }


        public enum Nakliyat
        {
            Ambar_Kargo = 301,
            Asansörlü_Nakliyat = 302,
            Depo_Kiralama = 303,
            Düğün_Servis_Kiralama = 304,
            Eşya_Depolama = 305,
            Eşya_Taşıma = 306,
            Ev_İçi_Eşya_Taşıma = 307,
            Ev_Taşıma = 308,
            Evden_Eve_Nakliyat = 309,
            Günlük_Şoför = 310,
            Havaalanı_Transfer = 311,
            Kamyonet_Kiralama = 312,
            Kamyonet_Nakliye = 313,
            Koltuk_Taşıma = 314,
            Minibüs_Kiralama = 315,
            Minivan_Nakliye = 316,
            Moto_Kurye = 317,
            Motosiklet_Taşıma = 318,
            Ofis_Taşıma = 319,
            Oto_Çekici = 320,
            Oto_Kurtarma = 321,
            Otobüs_Kiralama = 322,
            Özel_Şoför = 323,
            Paletli_Yük_Taşıma = 324,
            Panelvan_Nakliye = 325,
            Personel_Servisi = 326,
            Şehir_İçi_Nakliye = 327,
            Şehirler_Arası_Motosiklet_Taşıma = 328,
            Şehirler_Arası_Nakliye = 329,
            Şöförlü_Araç_Kiralama = 330,
            Uluslararası_Nakliyat = 331
        }

        public enum MontajVeTamir
        {
            Asansör_Bakım = 401,
            Avize_Montaj = 402,
            Bilgisayar_Tamiri = 403,
            Cam_Kestirme = 404,
            Cep_Telefonu_Tamiri = 405,
            Çanak_Anten_Kurulumu = 406,
            Çelik_Kapı_Montajı = 407,
            Çelik_Kapı_Tamiri = 408,
            Çilingir_Kapı_Açma = 409,
            Dolap_Tamiri = 410,
            Duvara_Raf_Montajı = 411,
            Elektrik_Hattı_Çekme = 412,
            Elektrik_Montaj = 413,
            Elektrik_Proje_Çizimi = 414,
            Elektrik_Tamiri = 415,
            Elektrik_Tesisatı = 416,
            Fiber_Kablo_Çekimi = 417,
            Gömme_Rezervuar_Tamiri = 418,
            iPhone_Tamiri = 419,
            Kablo_ve_Hat_Çekme = 420,
            Kamera_Güvenlik_Sistemleri = 421,
            Klima_Montaj = 422,
            Klima_Tamiri = 423,
            Klima_Temizliği = 424,
            Klozet_Tamiri = 425,
            Kombi_Bakım = 426,
            Kombi_Montaj = 427,
            Kombi_Petek_Temizleme = 428,
            Kombi_Tamiri = 429,
            Korniş_Montaj = 430,
            Mobilya_Sökme_ve_Montaj = 431,
            Musluk_Tamiri = 432,
            Panjur_Tamiri = 433,
            Pencere_Tamiri = 434,
            Petek_Montajı = 435,
            Petek_Tamiri = 436,
            Petek_Temizliği = 437,
            Sifon_Tamiri = 438,
            Su_Arıtma_Filtre_Değişimi = 439,
            Su_Arıtma_Montaj = 440,
            Su_Kaçağı_Tamiri = 441,
            Su_Kaçağı_Tespiti = 442,
            Su_Tesisatı_Döşeme = 443,
            Su_Tesisatı_Montaj = 444,
            Tıkanıklık_Açma = 445,
            TV_Tamiri = 446
        }

        public enum Organizasyon
        {
            ACILIS_ORGANIZASYONU = 501,
            ANIMATOR = 502,
            BANDO_TAKIMI = 503,
            BUTIK_PASTA = 504,
            CANLI_MUZIK = 505,
            CATERING = 506,
            DANSOZ_KIRALAMA = 507,
            DAVUL_ZURNACI_KIRALAMA = 508,
            DJ = 509,
            DOGUM_GUNU_ORGANIZASYONU = 510,
            DOGUM_GUNU_PASTASI = 511,
            DUGUN_ORGANIZASYON = 512,
            DUGUN_YEMEGI = 513,
            EVLILIK_TEKLIFI_ORGANIZASYON = 514,
            GARSON_KIRALAMA = 515,
            GELIN_ARABASI_KIRALAMA = 516,
            GELINLIK_DIKIMI = 517,
            GELINLIK_KIRALAMA = 518,
            HASTANE_ODASI_SUSLEME = 519,
            KEMANCI_KIRALAMA = 520,
            KINA_ORGANIZASYON = 521,
            KLASIK_ARABA_KIRALAMA = 522,
            LOKMA_DOKTURME = 523,
            MASA_SANDALYE_KIRALAMA = 524,
            MEVLUT_YEMEGI = 525,
            MUZISYEN = 526,
            NISAN_ORGANIZASYON = 527,
            NISAN_PASTASI = 528,
            PALYACO = 529,
            SES_SISTEMI_KIRALAMA = 530,
            SIHIRBAZ = 531,
            SOZ_ORGANIZASYON = 532,
            SUNNET_ORGANIZASYON = 533,
            TEMSILI_NIKAH_MEMURU = 534,
            YAS_PASTA = 535,
            YAT_KIRALAMA = 536,
            YATTA_EVLILIK_TEKLIFI = 537
        }





    }
}
